/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pact;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum HTTPMethod implements org.apache.thrift.TEnum {
  COPY(0),
  DELETE(1),
  GET(2),
  HEAD(3),
  OPTIONS(4),
  MOVE(5),
  PATCH(6),
  POST(7),
  PUT(8),
  TRACE(9);

  private final int value;

  private HTTPMethod(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static HTTPMethod findByValue(int value) { 
    switch (value) {
      case 0:
        return COPY;
      case 1:
        return DELETE;
      case 2:
        return GET;
      case 3:
        return HEAD;
      case 4:
        return OPTIONS;
      case 5:
        return MOVE;
      case 6:
        return PATCH;
      case 7:
        return POST;
      case 8:
        return PUT;
      case 9:
        return TRACE;
      default:
        return null;
    }
  }
}
